country_names = {
    "NO": "Norway",
    "UK": "United Kingdom",
    "DE": "Germany",
    "FR": "France",
    "IT": "Italy",
    "ES": "Spain",
    "SE": "Sweden",
    "NL": "Netherlands",
    "BE": "Belgium",
    "DK": "Denmark",
    "AT": "Austria",
    "FI": "Finland",
    "PL": "Poland",
    "CH": "Switzerland",
    "IE": "Ireland",
    "PT": "Portugal",
    "CZ": "Czech Republic",
    "GR": "Greece",
    "HU": "Hungary",
    "RO": "Romania",
    "SI": "Slovenia",
    "LV": "Latvia",
    "EE": "Estonia",
    "LT": "Lithuania",
    "CY": "Cyprus",
    "EL": "Greece",
    "BG": "Bulgaria",
    "TR": "Turkey",
    "IS": "Iceland",
    "RS": "Serbia",
    "HR": "Croatia",
    "LU": "Luxembourg",
    "SK": "Slovakia",
    "ZA": "South Africa",
    "TW": "Taiwan",
    "IL": "Israel",
    "KR": "South Korea",
    "US": "United States",
    "MY": "Malaysia",
    "IN": "India",
    "TH": "Thailand",
    "BR": "Brazil",
    "CA": "Canada",
    "AR": "Argentina",
    "EC": "Ecuador",
    "CO": "Colombia",
    "UY": "Uruguay",
    "BY": "Belarus"
    # Add more as needed
}